### PR TITLE
fix npd when resources is empty

### PR DESCRIPTION
**Pull request by mmyjona**

### CODE REVIEW

**Comment by rkusa** [comment]
Thanks for the PR. I am not sure if a `return` there is the best way to abort since we might still need e.g. https://github.com/rkusa/pdfjs/blob/3292218b4dc079b0ece864a3a8c553c1dac7c5b2/lib/external.js#L125-L130

Do you maybe have a small PDF that could be added to this repo as a test case? If so, feel free to send it to me per mail (mail address can be found on my Github profile).

**Comment by mmyjona** [comment]
i add some log and found something strange.
the npd stacktrace is as follow:

> TypeError: Cannot read property 'toString' of undefined
    at /home/toor/pc/backend/html2pdf/node_modules/pdfjs/lib/external.js:131:37
    at Array.map (<anonymous>)
    at ExternalDocument.setAsTemplate (/home/toor/pc/backend/html2pdf/node_modules/pdfjs/lib/external.js:131:26)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Document.end (/home/toor/pc/backend/html2pdf/node_modules/pdfjs/lib/document.js:526:5)
    at async processTarget (/home/toor/pc/backend/html2pdf/index.js:127:5)
    at async /home/toor/pc/backend/html2pdf/index.js:172:5

im using pdf-merger-js package but when i extract the call site from it. It's simply a call like:

> merger.doc.pipe(fs.createWriteStream(mergedPdf));
    await merger.doc.end();

I added some log at [https://github.com/rkusa/pdfjs/blob/master/lib/external.js#L101](external.js). And found the last loop of my pdf merging loops has different first and page object here.

Normal first variable is like 

> PDFDictionary {
  dictionary: {
    '/Type': PDFName { name: 'Page' },
    '/Resources': PDFDictionary { dictionary: [Object] },
    '/MediaBox': [ 0, 0, 594.95996, 841.91998, toString: [Function] ],
    '/Contents': PDFReference { object: [Getter] },
    '/StructParents': 0,
    '/Parent': PDFReference { object: [Getter] }
  }
}

and page is:

> PDFObject {
  id: null,
  rev: 0,
  properties: PDFDictionary {
    dictionary: {
      '/Type': [PDFName],
      '/Resources': [PDFDictionary],
      '/MediaBox': [Array],
      '/Contents': [PDFReference],
      '/StructParents': 0,
      '/Parent': [PDFReference]
    }
  },
  reference: PDFReference { object: [Getter] },
  content: null
}

In the loop causing the npd crash, the first variable is like:

> PDFDictionary {
  dictionary: {
    '/Type': PDFName { name: 'Pages' },
    '/Count': 8,
    '/Kids': [
      [PDFReference],
      [PDFReference],
      [PDFReference],
      [PDFReference],
      [PDFReference],
      [PDFReference],
      [PDFReference],
      [PDFReference],
      toString: [Function]
    ],
    '/Parent': PDFReference { object: [Getter] }
  }
}

and page variable is：

> PDFObject {
  id: null,
  rev: 0,
  properties: PDFDictionary {
    dictionary: {
      '/Type': [PDFName],
      '/Count': 8,
      '/Kids': [Array],
      '/Parent': [PDFReference]
    }
  },
  reference: PDFReference { object: [Getter] },
  content: null
}

My script is to merge multiple pdf generated with puppeteer. Any idea how can I debug it further?

**Comment by rkusa** [comment]
From the log output I could see that the issue has to do with nested page objects. Something I had fixed for adding pages to a document in #117, but apparently not when using such documents as templates. It should be fixed on `master`, can you try again?

**Comment by mmyjona** [comment]
> From the log output I could see that the issue has to do with nested page objects. Something I had fixed for adding pages to a document in #117, but apparently not when using such documents as templates. It should be fixed on `master`, can you try again?

Yes, it's fixed in master.

**Comment by rkusa** [comment]
Thanks for testing! I've published the fix as version 2.3.2

**Pull request closed without merging**
